// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: paxos.proto

package paxospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A ballot number. Ordered first by round, then by node_id as tiebreaker.
// This guarantees no two nodes ever use the same ballot.
type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Ballot) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Ballot) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        uint64                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      uint64                 `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Transaction) GetReceiver() uint64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ---- Phase 1 ----
type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	FromSlot      uint64                 `protobuf:"varint,2,opt,name=from_slot,json=fromSlot,proto3" json:"from_slot,omitempty"` // first log slot the proposer wants to claim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *PrepareRequest) GetFromSlot() uint64 {
	if x != nil {
		return x.FromSlot
	}
	return 0
}

type AcceptedEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Value         *Transaction           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedEntry) Reset() {
	*x = AcceptedEntry{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedEntry) ProtoMessage() {}

func (x *AcceptedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedEntry.ProtoReflect.Descriptor instead.
func (*AcceptedEntry) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedEntry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptedEntry) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptedEntry) GetValue() *Transaction {
	if x != nil {
		return x.Value
	}
	return nil
}

type PromiseResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ok       bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Promised *Ballot                `protobuf:"bytes,2,opt,name=promised,proto3" json:"promised,omitempty"` // acceptor's current promise (useful on rejection)
	// Entries this acceptor already accepted at/after from_slot.
	// A new leader MUST adopt these (highest ballot wins per slot).
	Accepted      []*AcceptedEntry `protobuf:"bytes,3,rep,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseResponse) Reset() {
	*x = PromiseResponse{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResponse) ProtoMessage() {}

func (x *PromiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResponse.ProtoReflect.Descriptor instead.
func (*PromiseResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *PromiseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PromiseResponse) GetPromised() *Ballot {
	if x != nil {
		return x.Promised
	}
	return nil
}

func (x *PromiseResponse) GetAccepted() []*AcceptedEntry {
	if x != nil {
		return x.Accepted
	}
	return nil
}

// ---- Phase 2 ----
type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Value         *Transaction           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptRequest) GetValue() *Transaction {
	if x != nil {
		return x.Value
	}
	return nil
}

type AcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Promised      *Ballot                `protobuf:"bytes,2,opt,name=promised,proto3" json:"promised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedResponse) Reset() {
	*x = AcceptedResponse{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedResponse) ProtoMessage() {}

func (x *AcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedResponse.ProtoReflect.Descriptor instead.
func (*AcceptedResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcceptedResponse) GetPromised() *Ballot {
	if x != nil {
		return x.Promised
	}
	return nil
}

// ---- Commit / liveness ----
type CommitNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Value         *Transaction           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitNotice) Reset() {
	*x = CommitNotice{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitNotice) ProtoMessage() {}

func (x *CommitNotice) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitNotice.ProtoReflect.Descriptor instead.
func (*CommitNotice) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *CommitNotice) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitNotice) GetValue() *Transaction {
	if x != nil {
		return x.Value
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderBallot  *Ballot                `protobuf:"bytes,1,opt,name=leader_ballot,json=leaderBallot,proto3" json:"leader_ballot,omitempty"`
	LeaderId      uint32                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,3,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetLeaderBallot() *Ballot {
	if x != nil {
		return x.LeaderBallot
	}
	return nil
}

func (x *Heartbeat) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *Heartbeat) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{9}
}

// ---- Client API ----
type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           *Transaction           `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *ClientRequest) GetTxn() *Transaction {
	if x != nil {
		return x.Txn
	}
	return nil
}

type ClientReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReply) Reset() {
	*x = ClientReply{}
	mi := &file_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReply) ProtoMessage() {}

func (x *ClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReply.ProtoReflect.Descriptor instead.
func (*ClientReply) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *ClientReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClientReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *BalanceRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type BalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceReply) Reset() {
	*x = BalanceReply{}
	mi := &file_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceReply) ProtoMessage() {}

func (x *BalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceReply.ProtoReflect.Descriptor instead.
func (*BalanceReply) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *BalanceReply) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x12\x05paxos\"7\n" +
	"\x06Ballot\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x04R\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\x04R\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"T\n" +
	"\x0ePrepareRequest\x12%\n" +
	"\x06ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06ballot\x12\x1b\n" +
	"\tfrom_slot\x18\x02 \x01(\x04R\bfromSlot\"t\n" +
	"\rAcceptedEntry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\x06ballot\x18\x02 \x01(\v2\r.paxos.BallotR\x06ballot\x12(\n" +
	"\x05value\x18\x03 \x01(\v2\x12.paxos.TransactionR\x05value\"~\n" +
	"\x0fPromiseResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\bpromised\x18\x02 \x01(\v2\r.paxos.BallotR\bpromised\x120\n" +
	"\baccepted\x18\x03 \x03(\v2\x14.paxos.AcceptedEntryR\baccepted\"t\n" +
	"\rAcceptRequest\x12%\n" +
	"\x06ballot\x18\x01 \x01(\v2\r.paxos.BallotR\x06ballot\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12(\n" +
	"\x05value\x18\x03 \x01(\v2\x12.paxos.TransactionR\x05value\"M\n" +
	"\x10AcceptedResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12)\n" +
	"\bpromised\x18\x02 \x01(\v2\r.paxos.BallotR\bpromised\"L\n" +
	"\fCommitNotice\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.paxos.TransactionR\x05value\"\x7f\n" +
	"\tHeartbeat\x122\n" +
	"\rleader_ballot\x18\x01 \x01(\v2\r.paxos.BallotR\fleaderBallot\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\rR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x03 \x01(\x04R\vcommitIndex\"\x05\n" +
	"\x03Ack\"5\n" +
	"\rClientRequest\x12$\n" +
	"\x03txn\x18\x01 \x01(\v2\x12.paxos.TransactionR\x03txn\"3\n" +
	"\vClientReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x04R\x06itemId\"(\n" +
	"\fBalanceReply\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance2\xc6\x02\n" +
	"\tPaxosNode\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PromiseResponse\x127\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x17.paxos.AcceptedResponse\x12)\n" +
	"\x06Commit\x12\x13.paxos.CommitNotice\x1a\n" +
	".paxos.Ack\x12-\n" +
	"\rSendHeartbeat\x12\x10.paxos.Heartbeat\x1a\n" +
	".paxos.Ack\x122\n" +
	"\x06Submit\x12\x14.paxos.ClientRequest\x1a\x12.paxos.ClientReply\x128\n" +
	"\n" +
	"GetBalance\x12\x15.paxos.BalanceRequest\x1a\x13.paxos.BalanceReplyB\x19Z\x17paxosbank/proto/paxospbb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_paxos_proto_goTypes = []any{
	(*Ballot)(nil),           // 0: paxos.Ballot
	(*Transaction)(nil),      // 1: paxos.Transaction
	(*PrepareRequest)(nil),   // 2: paxos.PrepareRequest
	(*AcceptedEntry)(nil),    // 3: paxos.AcceptedEntry
	(*PromiseResponse)(nil),  // 4: paxos.PromiseResponse
	(*AcceptRequest)(nil),    // 5: paxos.AcceptRequest
	(*AcceptedResponse)(nil), // 6: paxos.AcceptedResponse
	(*CommitNotice)(nil),     // 7: paxos.CommitNotice
	(*Heartbeat)(nil),        // 8: paxos.Heartbeat
	(*Ack)(nil),              // 9: paxos.Ack
	(*ClientRequest)(nil),    // 10: paxos.ClientRequest
	(*ClientReply)(nil),      // 11: paxos.ClientReply
	(*BalanceRequest)(nil),   // 12: paxos.BalanceRequest
	(*BalanceReply)(nil),     // 13: paxos.BalanceReply
}
var file_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.PrepareRequest.ballot:type_name -> paxos.Ballot
	0,  // 1: paxos.AcceptedEntry.ballot:type_name -> paxos.Ballot
	1,  // 2: paxos.AcceptedEntry.value:type_name -> paxos.Transaction
	0,  // 3: paxos.PromiseResponse.promised:type_name -> paxos.Ballot
	3,  // 4: paxos.PromiseResponse.accepted:type_name -> paxos.AcceptedEntry
	0,  // 5: paxos.AcceptRequest.ballot:type_name -> paxos.Ballot
	1,  // 6: paxos.AcceptRequest.value:type_name -> paxos.Transaction
	0,  // 7: paxos.AcceptedResponse.promised:type_name -> paxos.Ballot
	1,  // 8: paxos.CommitNotice.value:type_name -> paxos.Transaction
	0,  // 9: paxos.Heartbeat.leader_ballot:type_name -> paxos.Ballot
	1,  // 10: paxos.ClientRequest.txn:type_name -> paxos.Transaction
	2,  // 11: paxos.PaxosNode.Prepare:input_type -> paxos.PrepareRequest
	5,  // 12: paxos.PaxosNode.Accept:input_type -> paxos.AcceptRequest
	7,  // 13: paxos.PaxosNode.Commit:input_type -> paxos.CommitNotice
	8,  // 14: paxos.PaxosNode.SendHeartbeat:input_type -> paxos.Heartbeat
	10, // 15: paxos.PaxosNode.Submit:input_type -> paxos.ClientRequest
	12, // 16: paxos.PaxosNode.GetBalance:input_type -> paxos.BalanceRequest
	4,  // 17: paxos.PaxosNode.Prepare:output_type -> paxos.PromiseResponse
	6,  // 18: paxos.PaxosNode.Accept:output_type -> paxos.AcceptedResponse
	9,  // 19: paxos.PaxosNode.Commit:output_type -> paxos.Ack
	9,  // 20: paxos.PaxosNode.SendHeartbeat:output_type -> paxos.Ack
	11, // 21: paxos.PaxosNode.Submit:output_type -> paxos.ClientReply
	13, // 22: paxos.PaxosNode.GetBalance:output_type -> paxos.BalanceReply
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
