// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: paxos.proto

package paxospb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosNode_Prepare_FullMethodName       = "/paxos.PaxosNode/Prepare"
	PaxosNode_Accept_FullMethodName        = "/paxos.PaxosNode/Accept"
	PaxosNode_Commit_FullMethodName        = "/paxos.PaxosNode/Commit"
	PaxosNode_SendHeartbeat_FullMethodName = "/paxos.PaxosNode/SendHeartbeat"
	PaxosNode_Submit_FullMethodName        = "/paxos.PaxosNode/Submit"
	PaxosNode_GetBalance_FullMethodName    = "/paxos.PaxosNode/GetBalance"
)

// PaxosNodeClient is the client API for PaxosNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosNodeClient interface {
	// Paxos (node <-> node)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseResponse, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedResponse, error)
	Commit(ctx context.Context, in *CommitNotice, opts ...grpc.CallOption) (*Ack, error)
	SendHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Ack, error)
	// Client (client <-> leader)
	Submit(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error)
}

type paxosNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosNodeClient(cc grpc.ClientConnInterface) PaxosNodeClient {
	return &paxosNodeClient{cc}
}

func (c *paxosNodeClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseResponse)
	err := c.cc.Invoke(ctx, PaxosNode_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptedResponse)
	err := c.cc.Invoke(ctx, PaxosNode_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Commit(ctx context.Context, in *CommitNotice, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PaxosNode_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) SendHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PaxosNode_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Submit(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, PaxosNode_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosNodeServer is the server API for PaxosNode service.
// All implementations must embed UnimplementedPaxosNodeServer
// for forward compatibility.
type PaxosNodeServer interface {
	// Paxos (node <-> node)
	Prepare(context.Context, *PrepareRequest) (*PromiseResponse, error)
	Accept(context.Context, *AcceptRequest) (*AcceptedResponse, error)
	Commit(context.Context, *CommitNotice) (*Ack, error)
	SendHeartbeat(context.Context, *Heartbeat) (*Ack, error)
	// Client (client <-> leader)
	Submit(context.Context, *ClientRequest) (*ClientReply, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceReply, error)
	mustEmbedUnimplementedPaxosNodeServer()
}

// UnimplementedPaxosNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosNodeServer struct{}

func (UnimplementedPaxosNodeServer) Prepare(context.Context, *PrepareRequest) (*PromiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosNodeServer) Accept(context.Context, *AcceptRequest) (*AcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosNodeServer) Commit(context.Context, *CommitNotice) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosNodeServer) SendHeartbeat(context.Context, *Heartbeat) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedPaxosNodeServer) Submit(context.Context, *ClientRequest) (*ClientReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedPaxosNodeServer) GetBalance(context.Context, *BalanceRequest) (*BalanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPaxosNodeServer) mustEmbedUnimplementedPaxosNodeServer() {}
func (UnimplementedPaxosNodeServer) testEmbeddedByValue()                   {}

// UnsafePaxosNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosNodeServer will
// result in compilation errors.
type UnsafePaxosNodeServer interface {
	mustEmbedUnimplementedPaxosNodeServer()
}

func RegisterPaxosNodeServer(s grpc.ServiceRegistrar, srv PaxosNodeServer) {
	// If the following call panics, it indicates UnimplementedPaxosNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosNode_ServiceDesc, srv)
}

func _PaxosNode_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitNotice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Commit(ctx, req.(*CommitNotice))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).SendHeartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Submit(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosNode_ServiceDesc is the grpc.ServiceDesc for PaxosNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosNode",
	HandlerType: (*PaxosNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _PaxosNode_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosNode_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PaxosNode_Commit_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _PaxosNode_SendHeartbeat_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _PaxosNode_Submit_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PaxosNode_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
